[package]
name = "compress-wasm"
version = "0.1.0"
edition = "2024"
description = "WASM Zstd decompression for noaide"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
zstd.workspace = true
